from . import help
from . import start
from . import BoshHendler
from . import KursHendler
from . import KasbHendler
from . import KursBackendHendler
from . import KursBoshqalarHendler
from . import KursFrontendHendler
from . import KasbBoshqalarHendler
from . import KasbSIHendler
from . import KasbFrontendHendler
from . import KasbDizaynHendler
from . import KasbFullstackHendler
from . import KasbMobilHendler
from . import KasbBackendHendler
from . import dispetcher